version: '3.1'
services:
  mysql:
    image: mysql:8.0.23
    container_name: pb_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: pb
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 3306:3306

  adminer:
    container_name: pb_adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pb_phpmyadmin
    restart: always
    ports:
      - 8000:80
    environment:
      # MYSQL_ROOT_PASSWORD: N*kHmD5]\^+k{#5K
      # PMA_USER: root
      # PMA_PASSWORD: N*kHmD5]\^+k{#5K
      # PMA_ARBITRARY: 1
      # MYSQL_USER: root
      # MYSQL_PASSWORD: password
      # PMA_HOST: some_rds.amazonaws.com
      PMA_HOST: mysql
      # PMA_PORT: 3306
    depends_on:
      - mysql
